### ISSUE TITLE
Gen BTC Address

### ISSUE THREAD

**Issue by msinkec** [sCrypt-Inc/cat-contracts#3]
Make genprivkey generate BTC address. Use `bitcore-lib-inquisition` and get rid of `bsv`submodule dependency.

https://github.com/sCrypt-Inc/cat-contracts/blob/master/tests/utils/privateKey.ts

**Comment by yusufidimaina9989** [comment]
https://github.com/sCrypt-Inc/cat-contracts/pull/5
